// Automatically generated by `raw_to_c_array.py'

#include "stdint.h"

#define DATA_LEN 1260

const int16_t voltage [DATA_LEN];

const int16_t dcurrent[DATA_LEN];

const int16_t current [DATA_LEN];

