#include "filter.h"
#include "highpass.h"

/*
 * Generated by DSPLib GUI
 *
 * Filter Parameters:
 *     Filter:  IIR DF1
 *     Type:  Highpass
 *     wc1:  40.0
 *     n:  4
 *
 * For use with DSPLib function msp_biquad_cascade_df1_q15 and code example
 * filter_ex3_biquad_cascade_df1_q15
 */

msp_biquad_df1_q15_coeffs highpass[2] = {
    {
        .b0 = _Q15(0.877769797753528),
        .b1By2 = _Q15(-1.755539595507056/2),
        .b2 = _Q15(0.877769797753528),
        .a1By2 = _Q15(1.822419553252915/2),
        .a2 = _Q15(-0.831520791488760)
    },
    {
        .b0 = _Q15(0.999969481490524),
        .b1By2 = _Q15(-2.000000000000000/2),
        .b2 = _Q15(0.999969481490524),
        .a1By2 = _Q15(1.917017499490300/2),
        .a2 = _Q15(-0.926591163762066)
    }
};
