#include "highpass.h"

/*
 * Generated by DSPLib GUI
 *
 * Filter Parameters:
 *     Filter:  IIR DF1
 *     Type:  Highpass
 *     wc1:  30.0
 *     n:  4
 *
 * For use with DSPLib function msp_biquad_cascade_df1_q15 and code example
 * filter_ex3_biquad_cascade_df1_q15
 */

msp_biquad_df1_q15_coeffs highpass[2] = {
    {
        .b0 = _Q15(0.906868893695387),
        .b1By2 = _Q15(-1.813737787390775/2),
        .b2 = _Q15(0.906868893695387),
        .a1By2 = _Q15(1.865603346994032/2),
        .a2 = _Q15(-0.870834579919949)
    },
    {
        .b0 = _Q15(0.999969481490524),
        .b1By2 = _Q15(-2.000000000000000/2),
        .b2 = _Q15(0.999969481490524),
        .a1By2 = _Q15(1.938957352652234/2),
        .a2 = _Q15(-0.944394273400414)
    }
};
