#! /usr/bin/env python3

import numpy as np

a = np.loadtxt("rawSamples.dat", dtype=int, comments="#", delimiter='\t')
voltage = a[:,1]
dcurrent = a[:,2]
current = a[:,3]

def write_array(f, a, name):
    s = "const int16_t " + name + "[" + str(len(current)) + "] =\n{\n  "
    for i,x in enumerate(a):
        if i % 10 == 0:
            s += "\n  "
        s += str(hex(x)) + ", "
    f.write(s)
    f.write("};\n\n")


with open("data.c", "w") as f:
    f.write("// Automatically generated by `raw_to_c_array.py'\n\n")
    f.write("#include \"stdint.h\"\n\n")
    f.write("// Raw voltage ADC samples:\n")
    write_array(f, voltage, 'voltage')
    f.write("// Raw derivative of current ADC samples:\n")
    write_array(f, dcurrent, 'dcurrent')
    f.write("// Raw integration calculation ADC samples:\n")
    write_array(f, current, 'current')
    f.close()
with open("data.h", "w") as f:
    f.write("// Automatically generated by `raw_to_c_array.py'\n\n")
    f.write("#include \"stdint.h\"\n\n")
    f.write("const int16_t voltage [" + str(len(voltage)) + "];\n\n")
    f.write("const int16_t dcurrent[" + str(len(dcurrent)) + "];\n\n")
    f.write("const int16_t current [" + str(len(current)) + "];\n\n")
    f.close()
