INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_POWERBLADE_UTILS PowerBlade_Utils)

FIND_PATH(
    POWERBLADE_UTILS_INCLUDE_DIRS
    NAMES PowerBlade_Utils/api.h
    HINTS $ENV{POWERBLADE_UTILS_DIR}/include
        ${PC_POWERBLADE_UTILS_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    POWERBLADE_UTILS_LIBRARIES
    NAMES gnuradio-PowerBlade_Utils
    HINTS $ENV{POWERBLADE_UTILS_DIR}/lib
        ${PC_POWERBLADE_UTILS_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(POWERBLADE_UTILS DEFAULT_MSG POWERBLADE_UTILS_LIBRARIES POWERBLADE_UTILS_INCLUDE_DIRS)
MARK_AS_ADVANCED(POWERBLADE_UTILS_LIBRARIES POWERBLADE_UTILS_INCLUDE_DIRS)

